In [26]:
import pandas as pd
import numpy as np
import pickle
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("./data.csv")

In [3]:
data.head()

query  label
0  <area draggable="true" ondragend="alert(1)">te...      0
1  <style>:target {transform: rotate(180deg);}</s...      0
2  <style>@keyframes slidein {}</style><option st...      0
3  <rt onbeforepaste="alert(1)" contenteditable>t...      0
4          <area onmouseenter="alert(1)">test</area>      0

In [4]:
data.dropna(inplace=True)

In [5]:
data.label.value_counts()

0    616
1    616
2    616
Name: label, dtype: int64

In [6]:
cv = CountVectorizer() 
cv_matrix = cv.fit_transform(data['query']) 
X = pd.DataFrame(cv_matrix.toarray(), columns=cv.get_feature_names())
y = data.label

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [8]:
model = RandomForestClassifier(n_estimators=350, max_depth=10, oob_score=0.5, n_jobs=-1, random_state=1)

In [9]:
model.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, n_estimators=350, n_jobs=-1, oob_score=0.5,
                       random_state=1)

In [10]:
model.score(X_train, y_train)

0.9512855209742895

In [11]:
model.score(X_test, y_test)

0.9324324324324325

In [34]:
with open('./model.pkl', 'wb') as fout:
    pickle.dump([cv, model], fout)

In [38]:
a = cv.transform(['<source onpointerrawupdate=alert(1)>XSS</source>']).toarray()
model.predict(a)

array([0])

In [39]:
a = cv.transform(['"union select 1,load_file(\'/etc/passwd\'),1,1,1;",1']).toarray()
model.predict(a)

array([1])

In [40]:
a = cv.transform(['anonymouse']).toarray()
model.predict(a)

array([2])